pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
]

webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("", include("pages.urls", namespace='pages'))
]

customer/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class Customer(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False)
    cnpj_document = models.CharField(max_length=20, null=False, blank=False)
    rg_document = models.CharField(max_length=20, null=True, blank=True)
    ie_number = models.CharField(max_length=20, null=True, blank=True)
    im_document = models.CharField(max_length=20, null=True, blank=True)
    address = models.CharField(max_length=400, null=False, blank=False)
    main_phone = PhoneNumberField(null=False, blank=False, unique=True)
    phone = PhoneNumberField(null=True, blank=True, unique=True)

orders/models.py
from django.db import models
from customer.models import Customer
from vehicle.models import Vehicle
from django.utils.timezone import now


class Orders(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    data = models.DateTimeField(default=now)
    payed = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class OrderItems(models.Model):
    order = models.ForeignKey(Orders, on_delete=models.CASCADE)
    quantity = models.IntegerField(null=True, blank=True)
    description = models.CharField(max_length=510, null=False, blank=False)
    price = models.DecimalField(null=False, blank=False)
    discount = models.DecimalField(default=0, null=False, blank=False)
    total_price = models.DecimalField(null=False, blank=False)

    def __str__(self):
        return self.name

pages/models.py
from allauth.account.adapter import DefaultAccountAdapter


class MyAccountAdapter(DefaultAccountAdapter):
    def is_open_for_signup(self, request):
        return False

vehicle/models.py
from django.db import models
from customer.models import Customer


class Vehicle(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False)
    model = models.CharField(max_length=255, null=False, blank=False)
    license_plate = models.CharField(max_length=255, null=False, blank=False, unique=True)
    mileage = models.CharField(max_length=255, null=False, blank=False)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

orders/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'home.html'

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">NéstorCar</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}NéstorCar{% endblock %}

{% block content %}
    Olá!
{% endblock %}